#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=run_baselines
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:30:00
#SBATCH --output=./slurm_out/baselines_%j.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

source activate baselines

# conda install -c conda-forge tensorflow=2.12.0 numpy=1.23.5 pandas=1.5.3 h5py=3.6.0 -y
python baselines/run_baselines.py