#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=run_baselines
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=12:00:00
#SBATCH --output=job_scripts/slurm_out/baselines/MultiVAE/steam_run%j.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

source activate baselines

python src/extensions/baselines/run_baselines.py --model 'MultiVAE' --dataset 'steam'